# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings

excerpt_separator: <!-- more -->


title: Lab of Embedded System
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/embedded_system" # the subpath of your site, e.g. /blog
#url: "http://zjutcs.gitee.io" # the base hostname & protocol for your site

timezone: Asia/Shanghai

paginate: 4
paginate_path: "/page:num/"

# About/contact
author:
  name:              Zhe Yang
  url:               
  email:             


# Build settings
markdown: kramdown

permalink: "/blog/:title"

plugins:
  - jekyll-paginate


